# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GradeCalc(object):
    def setupUi(self, GradeCalc):
        GradeCalc.setObjectName("GradeCalc")
        GradeCalc.resize(421, 402)
        self.centralwidget = QtWidgets.QWidget(parent=GradeCalc)
        self.centralwidget.setObjectName("centralwidget")
        self.label_total = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_total.setGeometry(QtCore.QRect(20, 10, 171, 51))
        self.label_total.setObjectName("label_total")
        self.label_score = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_score.setGeometry(QtCore.QRect(20, 80, 111, 16))
        self.label_score.setObjectName("label_score")
        self.label_result = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(80, 190, 261, 141))
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.input_total = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_total.setGeometry(QtCore.QRect(190, 20, 201, 31))
        self.input_total.setObjectName("input_total")
        self.input_score = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_score.setGeometry(QtCore.QRect(130, 70, 261, 31))
        self.input_score.setObjectName("input_score")
        self.button_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(140, 120, 131, 51))
        self.button_submit.setObjectName("button_submit")
        GradeCalc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=GradeCalc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 24))
        self.menubar.setObjectName("menubar")
        GradeCalc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=GradeCalc)
        self.statusbar.setObjectName("statusbar")
        GradeCalc.setStatusBar(self.statusbar)

        self.retranslateUi(GradeCalc)
        QtCore.QMetaObject.connectSlotsByName(GradeCalc)

    def retranslateUi(self, GradeCalc):
        _translate = QtCore.QCoreApplication.translate
        GradeCalc.setWindowTitle(_translate("GradeCalc", "MainWindow"))
        self.label_total.setText(_translate("GradeCalc", "Total number of students :"))
        self.label_score.setText(_translate("GradeCalc", "Enter score(s) :"))
        self.button_submit.setText(_translate("GradeCalc", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GradeCalc = QtWidgets.QMainWindow()
    ui = Ui_GradeCalc()
    ui.setupUi(GradeCalc)
    GradeCalc.show()
    sys.exit(app.exec())
